Element.GetSubComponents
SHKnudsen/DynamoRevit pull request #16
Opened 2019-11-28 16:31 UTC by SHKnudsen

### Purpose

Adding Element.GetSubComponents node to the Elements category and tests

### Reviewers

@radumg 

### FYIs

Dynamo test file:
![Element GetSubComponents](https://user-images.githubusercontent.com/13732445/69821037-70315980-11fa-11ea-8892-4b67027229d4.png)

2019-11-29 14:37 UTC, radumg requested changes

2019-11-29 14:37 UTC, radumg commented on src/Libraries/RevitNodes/Elements/Element.cs
> +                throw new ArgumentNullException(nameof(this.InternalElement));
move this to the private method below

2019-11-29 14:37 UTC, radumg commented on src/Libraries/RevitNodes/Elements/Element.cs
> +                throw new ArgumentNullException(nameof(this.InternalElement));
also use `string.IsNullOrWhitespace`

2019-11-29 14:37 UTC, radumg commented on src/Libraries/RevitNodes/Elements/Element.cs
> +                case "Stairs":
can we use the `Enums` or at least `const string` variables here ?

2019-11-29 14:37 UTC, radumg commented on src/Libraries/RevitNodes/Elements/Element.cs
> +                    if (stairComponentIds.Count == 0 || stairComponentIds == null)
the `stairComponentIds` would never be `null` cause we initialised a `new List<ElementId>` above.
safe to only use `.Count`

2019-11-29 14:37 UTC, radumg commented on src/Libraries/RevitNodes/Elements/Element.cs
> +                        throw new NullReferenceException(Properties.Resources.NoSubComponents);
use `InvalidOperationException` since it's not a null reference, apply to all uses below

2019-11-29 14:37 UTC, radumg commented on src/Libraries/RevitNodes/Elements/Element.cs
> +                    if (beamSystemComponentIds.Count == 0 || beamSystemComponentIds == null)
same here, list wouldn't be null

2019-11-29 14:37 UTC, radumg commented on src/Libraries/RevitNodes/Elements/Element.cs
> +                    componenets.AddRange(beamSystemComponenetElements);
components typo

2019-11-29 14:37 UTC, radumg commented on src/Libraries/RevitNodes/Elements/Element.cs
> +                    List<Element> beamSystemComponenetElements = beamSystemComponentIds.Select(id => Document.GetElement(id).ToDSType(true))
beamSystemComponenetElements : components typo

2019-11-29 14:37 UTC, radumg commented on src/Libraries/RevitNodes/Elements/Element.cs
> +                    List<ElementId> railingComponentIds = railingElement.GetHandRails().ToList();
let's be consistent : make a new empty list, then add to it. that way you don't have to check for `null` below and it'll be the same as the parts

2019-11-29 14:37 UTC, radumg commented on src/Libraries/RevitNodes/Elements/Element.cs
> +                    componenets.AddRange(railingComponenetElements);
typos again

2019-11-29 14:37 UTC, radumg commented on test/Libraries/RevitNodesTests/Elements/ElementTests.cs
> +            var wallSubComponentsException = Assert.Throws<System.NullReferenceException>(() => wall.GetSubComponents());
this line should be in `Act` since you're calling the API we're testing.

2019-12-01 16:27 UTC, SHKnudsen commented on src/Libraries/RevitNodes/Elements/Element.cs
> +                throw new ArgumentNullException(nameof(this.InternalElement));
not needed anymore as we use the `BuiltInCategory` of the element now

2019-12-02 14:50 UTC, radumg approved these changes

2019-12-02 14:51 UTC, merged