Element.element type by name
SHKnudsen/DynamoRevit pull request #17
Opened 2019-12-05 09:24 UTC by SHKnudsen

### Purpose

Adding Element.ElementTypeByName node to the Elements category and tests

### Reviewers

@radumg 

### FYIs

Not sure if we should add this node to a category of it own.
In the nodes list, this node is called `ElementType.ByName` which indicates it should be under the category `ElementType` but it is grouped under the `Element` category. The `ElementType` category does not exist so we would need to create it.

Will ask about this on the next demo meeting.

Dynamo test file:
![Element ElementTypeByName](https://user-images.githubusercontent.com/13732445/70221894-0b698800-1741-11ea-8006-65bd38cf637d.png)

2019-12-05 09:39 UTC, radumg requested changes
Looking good, minor changes to catch an edge case

2019-12-05 09:39 UTC, radumg commented on src/Libraries/RevitNodes/Elements/Element.cs
> +                .FirstOrDefault(x => x.Name == name).ToDSType(true);
`FirstOrDefault` returns `null` if it doesn't find anything, so the next chained method `ToDSType` could fail.

If we don't find anything, we should `throw NotFoundException`, which then makes it safe to move `.ToDSType` to the return statement

2019-12-05 09:39 UTC, radumg commented on src/Libraries/RevitNodes/Elements/Element.cs
> +                .FirstOrDefault(x => x.Name == name).ToDSType(true);
Also, `ToDSType` should normally be on the next line since it's the next method in the chain

2019-12-05 09:39 UTC, radumg commented on test/Libraries/RevitNodesTests/Elements/ElementTests.cs
> +            string emptyTypeName = "";
also add a test case for searching for a valid type name that can't be found , which would throw `NotFoundException`

2019-12-09 13:21 UTC, SHKnudsen commented
Closing this PR and moving it to a separate one.

2019-12-09 13:21 UTC, closed without merging